# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HPS_User' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HPS_User
    pod 'Alamofire', '~> 4.0’
    pod 'IQKeyboardManagerSwift'
    pod 'SwiftyJSON', '~> 4.2.0'
    pod 'SDWebImage', '~> 4.0'
    pod 'EZSwiftExtensions'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'PopOverMenu' 

end
